services:
  backend:
    build:
      context: ./backend
    container_name: django-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings
      - DB_HOST=db           # Hostname of the MySQL container
      - DB_PORT=3306          # Default MySQL port
      - DB_NAME=newdatabse   # Name of your database
      - DB_USER=root       # MySQL username
      - DB_PASSWORD=root # MySQL password
    depends_on:
      - db

  db:
    image: mysql:5.7  # You can use any MySQL version you prefer
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: newdatabse
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
